export const words = [
  {
    page: 1,
    word: [
      "Judgmental",
      "Incentives",
      "Compelling",
      "Fathom",
      "Anchored",
      "Persuasive",
      "Vice Versa",
      "Recession",
      "Inflation",
    ],
    short: [
      "Critical, unfair",
      "Motivations, rewards",
      "Convincing, strong",
      "Fully understand",
      "Firmly held",
      "Convincing",
      "The opposite",
      "Economic downturn",
      "Rising prices",
    ],
    long: [
      "Forming opinions that are harsh and often not fair.",
      "Things that encourage someone to do something.",
      "So strong it makes you believe it.",
      "To completely grasp something, often after deep thought.",
      "Firmly fixed or established; in this case, refers to strongly held beliefs.",
      "Able to persuade or convince someone of something.",
      "The opposite is also true; used to say the reverse of what was just stated.",
      "A period of economic decline, often marked by job losses and reduced economic activity.",
      "A general increase in prices and fall in the purchasing value of money.",
    ],
  },
  {
    page: 2,
    word: [
      "Prioritize",
      "Inwardly",
      "Recessions",
      "Complacent",
      "Fathom",
      "Recreating",
    ],
    short: [
      "Rank by importance",
      "Internally, secretly",
      "Economic downturns",
      "Smugly self-satisfied",
      "Understand completely",
      "Making something again",
    ],
    long: [
      "To decide which tasks or things are most important and deal with them first.",
      "In one's mind or heart; privately; secretly.",
      "Periods of economic decline, characterized by job losses and reduced economic activity.",
      "Too satisfied with oneself or one's achievements; showing smug or uncritical satisfaction with oneself or one's achievements.",
      "To understand something completely, often after much thought.",
      "Creating something anew or making a copy, in this case, the emotional experience.",
    ],
  },
  {
    page: 3,
    word: [
      "Model",
      "Impact",
      "Consequences",
      "Anchored",
      "Characteristics",
      "Inflation",
    ],
    short: [
      "Represent, simulate",
      "Affect, influence",
      "Results, effects",
      "Firmly fixed, strongly influenced",
      "Features, traits",
      "Rising prices",
    ],
    long: [
      "To create a representation of something, often using a mathematical or computer-based system.",
      "To have a significant effect on something or someone.",
      "The results or effects of an action or event.",
      "Secured or firmly fixed; in this context, strongly influenced by past experiences.",
      "Distinguishing features or qualities of something.",
      "A general increase in prices and fall in the purchasing value of money.",
    ],
  },
  {
    page: 4,
    word: [
      "Bear (risk)",
      "Coincided",
      "Generational",
      "Collapse (in rates)",
      "Tailwind",
      "Incinerators",
      "Adjusted for inflation",
    ],
    short: [
      "Accept, tolerate",
      "Occurred at the same time",
      "Spanning several generations",
      "Sharp decline, drop",
      "Favorable conditions, support",
      "Things that destroy or consume value",
      "Corrected for price increases over time",
    ],
    long: [
      "To accept or endure something unpleasant or difficult. In finance, it refers to the willingness to take on potential losses for possible gains.",
      "Happened at the same time.",
      "Affecting or typical of a generation (a group of people born and living around the same time).",
      "A sudden and significant decrease.",
      "A favorable circumstance or influence that helps someone or something move forward.",
      "Something that burns or destroys something completely; here, referring to assets losing value.",
      "To account for the effects of inflation on the value of money over time; showing the real increase, not just the nominal increase.",
    ],
  },
  {
    page: 5,
    word: [
      "Impressionable",
      "Base (of knowledge)",
      "Noticeably",
      "Crossed your mind",
    ],
    short: [
      "Easily influenced",
      "Foundation, core understanding",
      "Obviously, clearly",
      "Occurred to you, thought of",
    ],
    long: [
      "Easily influenced or shaped by others.",
      "The fundamental knowledge or understanding of a subject.",
      "In a way that is easy to see or notice.",
      "Came into your thoughts; considered.",
    ],
  },
  {
    page: 6,
    word: [
      "Caucasian",
      "Wiped out",
      "Bombed out",
      "Incentives",
      "Atrocious",
      "Sweat shops",
    ],
    short: [
      "Of European descent",
      "Completely destroyed",
      "Heavily damaged by bombs",
      "Motivations, encouragements",
      "Horrible, extremely bad",
      "Factories with poor working conditions",
    ],
    long: [
      "Relating to the peoples of Europe and their descendants; often used in demographic contexts.",
      "To completely destroy or eliminate something.",
      "Severely damaged by bombing raids.",
      "Things that encourage or motivate someone to do something.",
      "Extremely bad or unpleasant.",
      "Factories or workshops, typically in developing countries, with very poor working conditions for low pay.",
    ],
  },
  {
    page: 7,
    word: [
      "Exploited",
      "Infrastructure",
      "Intuitively",
      "Vastly",
      "Misinformed",
      "Rotten",
      "Misjudge",
    ],
    short: [
      "Taken advantage of",
      "Basic systems, framework",
      "Instinctively, instinctively",
      "Greatly, enormously",
      "Given wrong information",
      "Very bad, corrupt",
      "Incorrectly assess, mistake",
    ],
    long: [
      "To make use of someone or something in a way that is unfair or unjust.",
      "The basic physical and organizational structures and facilities (e.g., buildings, roads, power supplies) needed for the operation of a society or enterprise.",
      "By means of or in accordance with intuition (instinct, gut feeling).",
      "To a very great extent.",
      "Having received or having been influenced by incorrect information.",
      "Very bad or unpleasant.",
      "To make a wrong judgment about something.",
    ],
  },
  {
    page: 8,
    word: [
      "Prospects",
      "Crippling",
      "Tangible",
      "Subconscious",
      "Intuitively",
      "Persist",
      "Uncovers",
    ],
    short: [
      "Chances, possibilities",
      "Severely damaging, overwhelming",
      "Real, touchable",
      "Unconscious, unaware",
      "Instinctively, instinctively",
      "Continue to exist, continue to happen",
      "Reveals, exposes",
    ],
    long: [
      "The possibility or likelihood of something happening or being achieved.",
      "Causing severe damage or difficulty.",
      "That can be perceived or felt; real and not imaginary.",
      "Processes happening below the level of conscious awareness.",
      "By means of or in accordance with intuition (instinct, gut feeling).",
      "To continue to exist or happen despite problems or difficulties.",
      "To bring to light something that was previously hidden or unknown.",
    ],
  },
  {
    page: 9,
    word: [
      "Scrambled",
      "Narrative",
      "Misbehavior",
      "Foundation",
      "Concepts",
      "Entitled",
      "Participation",
    ],
    short: [
      "Mixed together haphazardly",
      "Story, account",
      "Bad or wrong conduct",
      "Basis, groundwork",
      "Ideas, principles",
      "Having a right to",
      "Involvement, taking part",
    ],
    long: [
      "Combined in a disorganized or confused way.",
      "A spoken or written account of connected events; a story.",
      "Actions that are considered wrong or unacceptable.",
      "The base or underlying structure of something.",
      "Abstract ideas; general notions.",
      "Having a right to something.",
      "The action of taking part in something.",
    ],
  },
  {
    page: 10,
    word: [
      "Pension",
      "Exceed",
      "Classified",
      "Exaggerated",
      "Dignified",
      "Reiterate",
      "Backbone",
      "Vehicle",
      "Fold (fourfold)",
    ],
    short: [
      "Regular payment after retirement",
      "Go beyond, surpass",
      "Categorized, grouped",
      "Overstated, overemphasized",
      "Respectful, honorable",
      "Repeat, restate",
      "Most important part, main support",
      "Means, method",
      "Multiple, increase by a factor of",
    ],
    long: [
      "A regular payment made during a person's retirement from an employer or a government.",
      "To be greater than a particular amount or value.",
      "To categorize or arrange something according to a particular system.",
      "To represent something as larger, better, or worse than it really is.",
      "Showing or expressing dignity and respect.",
      "To say something again or a number of times, typically for emphasis.",
      "The most important part or feature of something.",
      "A thing used to achieve a particular purpose.",
      "A multiple of; in this case, increase by a factor of four.",
    ],
  },
  {
    page: 11,
    word: [
      "Accumulated",
      "Winging it",
      "Acclimated",
      "Widespread",
      "Domesticated",
      "Retain",
      "Versus",
    ],
    short: [
      "Gathered, collected",
      "Improvising, doing something without a plan",
      "Adapted, adjusted",
      "Common, extensive",
      "Tamed, made suitable for human use",
      "Keep, maintain",
      "Against, in contrast to",
    ],
    long: [
      "To gradually gather or acquire something over a period of time.",
      "To do something without proper preparation or planning.",
      "To become adjusted to a new environment or situation.",
      "Found or distributed over a wide area or among a large number of people.",
      "To bring animals or plants under human control and care; to tame or train for human use.",
      "To continue to have or keep something.",
      "In contrast to; as opposed to.",
    ],
  },
];
