import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { NextUIProvider } from "@nextui-org/react";
import Header from "../components/Header";
import { BookProvider } from "@/context/bookContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-new-gr-c-s-check-loaded="14.1211.0" data-gr-ext-installed="">
        <BookProvider>
          <ClerkProvider>
            <NextUIProvider>
              <Header />
              {children}
            </NextUIProvider>
          </ClerkProvider>
        </BookProvider>
      </body>
    </html>
  );
}
