import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Header from "../components/Header";
import { BookProvider } from "@/context/bookContext";
import { HeroUIProvider } from "@heroui/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Lumia - The Storyteller",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.jpg', // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeroUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="system">
            <BookProvider>
              {/* <ClerkProvider> */}
              <NextUIProvider>
                <Header />
                {children}
              </NextUIProvider>
              {/* </ClerkProvider> */}
            </BookProvider>
          </NextThemesProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
